CREATE DATABASE IF EXISTS clinica_fisioterapia;
USE clinica_fisioterapia;

-- =========================
-- CRIAÇÃO DAS TABELAS
-- =========================

CREATE TABLE DOMINIO_SEXO (
    ID_SEXO   INT         PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(30) NOT NULL
);

CREATE TABLE TIPO_EXAME (
    ID_TIPO_EXAME INT         PRIMARY KEY AUTO_INCREMENT,
    NOME_TIPO     VARCHAR(60) NOT NULL
);

CREATE TABLE TIPO_PLANO (
    ID_TIPO_PLANO INT         PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO     VARCHAR(50) NOT NULL
);

CREATE TABLE ESPECIALIDADE (
    ID_ESPECIALIDADE   INT          PRIMARY KEY AUTO_INCREMENT,
    NOME_ESPECIALIDADE VARCHAR(100) NOT NULL
);

CREATE TABLE FORMA_PAGAMENTO (
    ID_FORMA_PAGAMENTO INT         PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO          VARCHAR(50) NOT NULL
);

CREATE TABLE STATUS_SESSAO (
    ID_STATUS_SESSAO INT         PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO        VARCHAR(40) NOT NULL
);

CREATE TABLE PROCEDIMENTO (
    ID_PROCEDIMENTO   INT           PRIMARY KEY AUTO_INCREMENT,
    NOME_PROCEDIMENTO VARCHAR(100)  NOT NULL,
    VALOR_PADRAO      DECIMAL(10,2) NOT NULL
);

CREATE TABLE PLANO_SAUDE (
    ID_PLANO      INT         PRIMARY KEY AUTO_INCREMENT,
    NOME_PLANO    VARCHAR(50) NOT NULL,
    ID_TIPO_PLANO INT         NOT NULL
);

CREATE TABLE PACIENTE (
    ID_PACIENTE          INT          PRIMARY KEY AUTO_INCREMENT,
    NOME_COMPLETO        VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO      DATE         NOT NULL,
    ID_SEXO              INT          NOT NULL,
    DIAGNOSTICO_INICIAL  TEXT,
    INDICACAO_TRATAMENTO TEXT
);

CREATE TABLE ENDERECO_PACIENTE (
    ID_ENDERECO INT          PRIMARY KEY AUTO_INCREMENT,
    ID_PACIENTE INT          NOT NULL,
    LOGRADOURO  VARCHAR(100) NOT NULL,
    NUMERO      VARCHAR(10)  NOT NULL,
    COMPLEMENTO VARCHAR(60),
    BAIRRO      VARCHAR(60)  NOT NULL,
    CIDADE      VARCHAR(60)  NOT NULL,
    ESTADO      CHAR(2)      NOT NULL,
    CEP         CHAR(8)      NOT NULL
);

CREATE TABLE TELEFONE_PACIENTE (
    ID_TELEFONE INT         PRIMARY KEY AUTO_INCREMENT,
    ID_PACIENTE INT         NOT NULL,
    NUMERO      VARCHAR(20) NOT NULL,
    EH_WHATSAPP TINYINT(1)  DEFAULT 0
);

CREATE TABLE FISIOTERAPEUTA (
    ID_FISIOTERAPEUTA INT          PRIMARY KEY AUTO_INCREMENT,
    NOME              VARCHAR(100) NOT NULL,
    ID_ESPECIALIDADE  INT          NOT NULL,
    TELEFONE          VARCHAR(20),
    EMAIL             VARCHAR(100),
    AGENDA_TRABALHO   TEXT
);

CREATE TABLE SESSAO_AGENDA (
    ID_SESSAO          INT           PRIMARY KEY AUTO_INCREMENT,
    ID_PACIENTE        INT           NOT NULL,
    ID_FISIOTERAPEUTA  INT           NOT NULL,
    ID_PROCEDIMENTO    INT           NOT NULL,
    ID_PLANO           INT           NULL,
    ID_STATUS_SESSAO   INT           NOT NULL,
    ID_FORMA_PAGAMENTO INT           NULL,
    DATA_SESSAO        DATE          NOT NULL,
    HORA_SESSAO        TIME          NOT NULL,
    VALOR_REAL_PAGO    DECIMAL(10,2)
);

CREATE TABLE AVALIACAO (
    ID_AVALIACAO         INT  PRIMARY KEY AUTO_INCREMENT,
    ID_PACIENTE          INT  NOT NULL,
    ID_FISIOTERAPEUTA    INT  NOT NULL,
    DATA_AVALIACAO       DATE NOT NULL,
    DESCRICAO_AVALIACAO  TEXT,
    PROGRESSO_PERCENTUAL INT,
    RECOMENDACAO         TEXT
);

CREATE TABLE EXAME (
    ID_EXAME        INT          PRIMARY KEY AUTO_INCREMENT,
    ID_PACIENTE     INT          NOT NULL,
    ID_TIPO_EXAME   INT          NOT NULL,
    DATA_EXAME      DATE         NOT NULL,
    RESULTADO_LAUDO TEXT,
    CAMINHO_IMAGEM  VARCHAR(255)
);

-- =========================
-- CRIAÇÃO DAS FOREIGN KEYS
-- =========================

ALTER TABLE PLANO_SAUDE
    ADD CONSTRAINT FK_PLANO_TIPO FOREIGN KEY (ID_TIPO_PLANO) REFERENCES TIPO_PLANO(ID_TIPO_PLANO);

ALTER TABLE PACIENTE
    ADD CONSTRAINT FK_PAC_SEXO FOREIGN KEY (ID_SEXO) REFERENCES DOMINIO_SEXO(ID_SEXO);

ALTER TABLE ENDERECO_PACIENTE
    ADD CONSTRAINT FK_END_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE);

ALTER TABLE TELEFONE_PACIENTE
    ADD CONSTRAINT FK_PAC_FONE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE);

ALTER TABLE FISIOTERAPEUTA
    ADD CONSTRAINT FK_FISIO_ESPEC FOREIGN KEY (ID_ESPECIALIDADE) REFERENCES ESPECIALIDADE(ID_ESPECIALIDADE);

ALTER TABLE SESSAO_AGENDA
    ADD CONSTRAINT FK_AGENDA_PACIENTE  FOREIGN KEY (ID_PACIENTE)        REFERENCES PACIENTE(ID_PACIENTE),
    ADD CONSTRAINT FK_AGENDA_FISIO     FOREIGN KEY (ID_FISIOTERAPEUTA)  REFERENCES FISIOTERAPEUTA(ID_FISIOTERAPEUTA),
    ADD CONSTRAINT FK_AGENDA_PROC      FOREIGN KEY (ID_PROCEDIMENTO)    REFERENCES PROCEDIMENTO(ID_PROCEDIMENTO),
    ADD CONSTRAINT FK_AGENDA_PLANO     FOREIGN KEY (ID_PLANO)           REFERENCES PLANO_SAUDE(ID_PLANO),
    ADD CONSTRAINT FK_AGENDA_STATUS    FOREIGN KEY (ID_STATUS_SESSAO)   REFERENCES STATUS_SESSAO(ID_STATUS_SESSAO),
    ADD CONSTRAINT FK_AGENDA_PAGAMENTO FOREIGN KEY (ID_FORMA_PAGAMENTO) REFERENCES FORMA_PAGAMENTO(ID_FORMA_PAGAMENTO);

ALTER TABLE AVALIACAO
    ADD CONSTRAINT FK_PAC_AVAL   FOREIGN KEY (ID_PACIENTE)       REFERENCES PACIENTE(ID_PACIENTE),
    ADD CONSTRAINT FK_FISIO_AVAL FOREIGN KEY (ID_FISIOTERAPEUTA) REFERENCES FISIOTERAPEUTA(ID_FISIOTERAPEUTA);

ALTER TABLE EXAME
    ADD CONSTRAINT FK_PAC_EXAME  FOREIGN KEY (ID_PACIENTE)   REFERENCES PACIENTE(ID_PACIENTE),
    ADD CONSTRAINT FK_EXAME_TIPO FOREIGN KEY (ID_TIPO_EXAME) REFERENCES TIPO_EXAME(ID_TIPO_EXAME);
