-- TRABALHO FINAL - AMBIENTE DE DADOS
-- CENÁRIO 8 - CLÍNICA DE FISIOTERAPIA
-- ETAPA 3 - CRIAÇÃO DO BANCO DE DADOS
-- ============================================================

-- ------------------------------------------------------------
-- PARTE 1: CRIAÇÃO DO BANCO E SELEÇÃO
-- ------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS clinica_fisioterapia;

USE clinica_fisioterapia;

-- ------------------------------------------------------------
-- PARTE 2: CRIAÇÃO DAS TABELAS (sem FKs)
-- ------------------------------------------------------------

-- CORREÇÃO: TELEFONE_PACIENTE passa a ser atributo direto da entidade PACIENTE,
-- da mesma forma que ocorre na entidade FISIOTERAPEUTA.
-- A tabela separada TELEFONE_PACIENTE foi removida conforme orientação do professor.

CREATE TABLE PACIENTE (
    ID_PACIENTE           INT           PRIMARY KEY AUTO_INCREMENT,
    NOME_COMPLETO         VARCHAR(100)  NOT NULL,
    DATA_NASCIMENTO       DATE          NOT NULL,
    SEXO                  CHAR(1)       NOT NULL,
    ENDERECO              VARCHAR(200),
    TELEFONE_PACIENTE     VARCHAR(20),
    DIAGNOSTICO_INICIAL   TEXT,
    INDICACAO_TRATAMENTO  TEXT
);

CREATE TABLE FISIOTERAPEUTA (
    ID_FISIOTERAPEUTA  INT           PRIMARY KEY AUTO_INCREMENT,
    NOME               VARCHAR(100)  NOT NULL,
    ESPECIALIDADE      VARCHAR(50),
    TELEFONE           VARCHAR(20),
    EMAIL              VARCHAR(100),
    AGENDA_TRABALHO    TEXT
);

CREATE TABLE PLANO_SAUDE (
    ID_PLANO    INT          PRIMARY KEY AUTO_INCREMENT,
    NOME_PLANO  VARCHAR(50)  NOT NULL,
    TIPO_PLANO  VARCHAR(50)
);

CREATE TABLE PROCEDIMENTO (
    ID_PROCEDIMENTO    INT            PRIMARY KEY AUTO_INCREMENT,
    NOME_PROCEDIMENTO  VARCHAR(100)   NOT NULL,
    DESCRICAO          TEXT,
    VALOR_PADRAO       DECIMAL(10,2)  NOT NULL
);

CREATE TABLE SESSAO (
    ID_SESSAO            INT            PRIMARY KEY AUTO_INCREMENT,
    DATA_SESSAO          DATETIME       NOT NULL,
    VALOR_PROCEDIMENTO   DECIMAL(10,2),
    MODALIDADE_PAGAMENTO VARCHAR(30),
    PAGO                 TINYINT(1)     DEFAULT 0,
    ID_PACIENTE          INT            NOT NULL,
    ID_FISIOTERAPEUTA    INT            NOT NULL,
    ID_PROCEDIMENTO      INT            NOT NULL,
    ID_PLANO             INT
);

CREATE TABLE AVALIACAO (
    ID_AVALIACAO         INT     PRIMARY KEY AUTO_INCREMENT,
    ID_PACIENTE          INT     NOT NULL,
    ID_FISIOTERAPEUTA    INT     NOT NULL,
    DATA_AVALIACAO       DATE    NOT NULL,
    AVALIACAO            TEXT,
    PROGRESSO_PERCENTUAL INT,
    RECOMENDACAO         TEXT
);

CREATE TABLE EXAME (
    ID_EXAME        INT          PRIMARY KEY AUTO_INCREMENT,
    ID_PACIENTE     INT          NOT NULL,
    TIPO_EXAME      VARCHAR(50),
    DATA_EXAME      DATE         NOT NULL,
    RESULTADO_LAUDO TEXT,
    IMAGEM_EXAME    VARCHAR(255)
);

-- ------------------------------------------------------------
-- PARTE 3: CRIAÇÃO DAS FOREIGN KEYS (separado conforme pedido)
-- ------------------------------------------------------------

ALTER TABLE SESSAO
    ADD CONSTRAINT FK_PAC_SESSAO
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE);

ALTER TABLE SESSAO
    ADD CONSTRAINT FK_FISIO_SESSAO
    FOREIGN KEY (ID_FISIOTERAPEUTA) REFERENCES FISIOTERAPEUTA(ID_FISIOTERAPEUTA);

ALTER TABLE SESSAO
    ADD CONSTRAINT FK_PROC_SESSAO
    FOREIGN KEY (ID_PROCEDIMENTO) REFERENCES PROCEDIMENTO(ID_PROCEDIMENTO);

ALTER TABLE SESSAO
    ADD CONSTRAINT FK_PLANO_SESSAO
    FOREIGN KEY (ID_PLANO) REFERENCES PLANO_SAUDE(ID_PLANO);

ALTER TABLE AVALIACAO
    ADD CONSTRAINT FK_PAC_AVAL
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE);

ALTER TABLE AVALIACAO
    ADD CONSTRAINT FK_FISIO_AVAL
    FOREIGN KEY (ID_FISIOTERAPEUTA) REFERENCES FISIOTERAPEUTA(ID_FISIOTERAPEUTA);

ALTER TABLE EXAME
    ADD CONSTRAINT FK_PAC_EXAME
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE);

-- ------------------------------------------------------------
-- PARTE 4: VERIFICAÇÃO (consultas para conferência)
-- ------------------------------------------------------------

SHOW TABLES;

DESC SESSAO;

SELECT TABLE_NAME, CONSTRAINT_NAME, REFERENCED_TABLE_NAME
FROM information_schema.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = 'clinica_fisioterapia'
  AND REFERENCED_TABLE_NAME IS NOT NULL;
