USE clinica_fisioterapia;

-- =========================
-- RELATÓRIO DE SESSÕES
-- =========================
SELECT
    s.ID_SESSAO,
    s.DATA_SESSAO,
    p.NOME_COMPLETO AS PACIENTE,
    f.NOME AS FISIOTERAPEUTA,
    pr.NOME_PROCEDIMENTO,
    pl.NOME_PLANO,
    s.MODALIDADE_PAGAMENTO,
    s.PAGO,
    s.VALOR_PROCEDIMENTO
FROM SESSAO s
JOIN PACIENTE p ON s.ID_PACIENTE = p.ID_PACIENTE
JOIN FISIOTERAPEUTA f ON s.ID_FISIOTERAPEUTA = f.ID_FISIOTERAPEUTA
JOIN PROCEDIMENTO pr ON s.ID_PROCEDIMENTO = pr.ID_PROCEDIMENTO
LEFT JOIN PLANO_SAUDE pl ON s.ID_PLANO = pl.ID_PLANO
ORDER BY s.DATA_SESSAO;

-- =========================
-- PACIENTES
-- =========================
SELECT * FROM PACIENTE;

-- =========================
-- AVALIAÇÕES
-- =========================
SELECT
    a.ID_AVALIACAO,
    p.NOME_COMPLETO,
    f.NOME,
    a.DATA_AVALIACAO,
    a.AVALIACAO,
    a.PROGRESSO_PERCENTUAL,
    a.RECOMENDACAO
FROM AVALIACAO a
JOIN PACIENTE p ON a.ID_PACIENTE = p.ID_PACIENTE
JOIN FISIOTERAPEUTA f ON a.ID_FISIOTERAPEUTA = f.ID_FISIOTERAPEUTA;

-- =========================
-- EXAMES
-- =========================
SELECT
    e.ID_EXAME,
    p.NOME_COMPLETO,
    e.TIPO_EXAME,
    e.DATA_EXAME,
    e.RESULTADO_LAUDO
FROM EXAME e
JOIN PACIENTE p ON e.ID_PACIENTE = p.ID_PACIENTE;

-- =========================
-- FINANCEIRO
-- =========================
SELECT
    COUNT(*) AS TOTAL_SESSOES,
    SUM(VALOR_PROCEDIMENTO) AS RECEITA_TOTAL,
    SUM(CASE WHEN PAGO = 1 THEN VALOR_PROCEDIMENTO ELSE 0 END) AS RECEITA_RECEBIDA,
    SUM(CASE WHEN PAGO = 0 THEN VALOR_PROCEDIMENTO ELSE 0 END) AS RECEITA_PENDENTE
FROM SESSAO;

-- =========================
-- PRODUTIVIDADE
-- =========================
SELECT
    f.NOME,
    f.ESPECIALIDADE,
    COUNT(s.ID_SESSAO) AS TOTAL_SESSOES,
    SUM(s.VALOR_PROCEDIMENTO) AS FATURAMENTO
FROM FISIOTERAPEUTA f
LEFT JOIN SESSAO s ON s.ID_FISIOTERAPEUTA = f.ID_FISIOTERAPEUTA
GROUP BY f.ID_FISIOTERAPEUTA, f.NOME, f.ESPECIALIDADE;

-- =========================
-- PROCEDIMENTOS MAIS USADOS
-- =========================
SELECT
    pr.NOME_PROCEDIMENTO,
    COUNT(s.ID_SESSAO) AS QTD,
    SUM(s.VALOR_PROCEDIMENTO) AS FATURAMENTO
FROM PROCEDIMENTO pr
JOIN SESSAO s ON pr.ID_PROCEDIMENTO = s.ID_PROCEDIMENTO
GROUP BY pr.ID_PROCEDIMENTO, pr.NOME_PROCEDIMENTO;

-- =========================
-- PACIENTES COM MAIS SESSÕES
-- =========================
SELECT
    p.NOME_COMPLETO,
    COUNT(s.ID_SESSAO) AS TOTAL,
    SUM(s.VALOR_PROCEDIMENTO) AS GASTO
FROM PACIENTE p
JOIN SESSAO s ON p.ID_PACIENTE = s.ID_PACIENTE
GROUP BY p.ID_PACIENTE, p.NOME_COMPLETO;

-- =========================
-- FORMAS DE PAGAMENTO
-- =========================
SELECT
    MODALIDADE_PAGAMENTO,
    COUNT(*) AS QUANTIDADE,
    SUM(VALOR_PROCEDIMENTO) AS TOTAL
FROM SESSAO
GROUP BY MODALIDADE_PAGAMENTO;
